# Generated by Django 5.0.6 on 2024-05-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
